global TIME_INQUIRE_REPORT_DELAY_SEC
TIME_INQUIRE_REPORT_DELAY_SEC = 0.130

global TIME_OPEN_BROWSER_SEC
TIME_OPEN_BROWSER_SEC = 0.2

global TIME_SEND_REPORT_DELAY_SEC
TIME_SEND_REPORT_DELAY_SEC = 3

# global TIME_WAIT_REPORT_RESPONSE_SEC
# TIME_WAIT_REPORT_RESPONSE_SEC = 1

global TIME_SCREENSHOT_WAIT_TIME
TIME_SCREENSHOT_WAIT_TIME = 5
